apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-tgepsijh
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-tgepsijh:e2c34f1b616f3a3dca77a8a10eed6b181264c5c2@sha256:8b388fe45cae806c9a20cd152bc0d9081cc149b27c6d431ed07fff571ee572cf
        name: container-image  
